/*
 * File: app/store/GoodInfo.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pdsencha.store.GoodInfo', {
    extend: 'Ext.data.Store',
    alias: 'store.goodinfo',

    requires: [
        'pdsencha.model.GoodInfo',
        'Ext.data.proxy.Memory'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                title: '母乳无可替代',
                info: '母乳是目前最安全，最天然的宝宝食物！',
                image: './resources/images/mr.jpg'
            },
            {
                title: '母乳无可替代',
                info: '母乳喂养，不仅能增强母女感情，还能提高宝宝免疫力！',
                image: './resources/images/mr1.jpg'
            },
            {
                title: '母乳无可替代',
                info: '母乳分泌不畅的妈妈可以采用物理方法催奶！',
                image: './resources/images/mr2.jpg'
            },
            {
                title: '母乳无可替代1',
                info: '黄花菜是中国传统的催奶食物，催奶效果堪称神奇！',
                image: './resources/images/mr3.jpg'
            },
            {
                title: '母乳无可替代1',
                info: '木瓜也是天然的催奶食物，哺乳期的妈妈可以定期吃一吃木瓜炖雪蛤！',
                image: './resources/images/mr4.jpg'
            }
        ],
        groupField: 'title',
        model: 'pdsencha.model.GoodInfo',
        storeId: 'GoodInfo',
        proxy: {
            type: 'memory'
        }
    }
});