/*
 * File: app/view/aboutDev.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pdsencha.view.aboutDev', {
    extend: 'Ext.Panel',
    alias: 'widget.aboutdev',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label',
        'Ext.Img'
    ],

    config: {
        padding: '1.2em',
        scrollable: true,
        cls: 'info-panel',
        itemId:'pnl_aboutdev',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.animateActiveItem('mainview', { type: 'slide', direction: 'right' });
                        },
                        docked: 'left',
                        itemId: 'btnback',
                        padding: 5,
                        ui: 'back',
                        text: '返回',
                        style:{
                            'font-size':'1em'
                        }
                    },
                    {
                        xtype: 'spacer',
                        docked: 'right',
                        width: 50
                    },
                    {
                        xtype: 'label',
                        html: '关于开发者',
                        style: {
                            color: '#FFF',
                            'font-size': '1em',
                            'text-align': 'center'
                        },
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'container',
                margin: '20 0 0 0',
                items: [
                    {
                        xtype: 'container',
                        height: 203,
                        margin: '20 0 0 0',
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                width: '100%',
                                src: './resources/images/dev1.png'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: '视觉设计--语熙',
                        itemId: 'lbl_aboutdev',
                        style: {
                            'text-align': 'center',
                            'font-weight': 'bold',
                            color: '#FFF',
                            'padding-top': '0.5em'
                        }
                    },
                    {
                        xtype: 'label',
                        html: '喝过半年奶，上过两年学，喜欢看书、画画，对颜色很敏感，是喜欢晚睡晚起的小天使。',
                        itemId: 'lbl_aboutdev1',
                        style: {
                            'font-algin': 'center',
                            color: '#FFF'
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                margin: '20 0 0 0',
                items: [
                    {
                        xtype: 'container',
                        height: 203,
                        margin: '20 0 0 0',
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                width: '100%',
                                src: './resources/images/dev2.png'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: '产品设计<br>IOS开发--Edgar',
                        itemId: 'lbl_aboutdev',
                        style: {
                            'text-align': 'center',
                            'font-weight': 'bold',
                            color: '#FFF',
                            'padding-top': '0.5em'
                        }
                    },
                    {
                        xtype: 'label',
                        html: '下过田，种过地，摆过地摊，写过程序，做过运营，尘世中一个迷途小书童。',
                        itemId: 'lbl_aboutdev1',
                        style: {
                            'font-algin': 'center',
                            color: '#FFF'
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                margin: '20 0 0 0',
                items: [
                    {
                        xtype: 'container',
                        height: 203,
                        margin: '20 0 0 0',
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                width: '100%',
                                src: './resources/images/dev3.png'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: 'Android开发--唐唐',
                        itemId: 'lbl_aboutdev',
                        style: {
                            'text-align': 'center',
                            'font-weight': 'bold',
                            color: '#FFF',
                            'padding-top': '0.5em'
                        }
                    },
                    {
                        xtype: 'label',
                        html: '除了钻研技术，没有其他任何爱好！尘世中一个迷途老码农。',
                        itemId: 'lbl_aboutdev1',
                        style: {
                            'font-algin': 'center',
                            color: '#FFF'
                        }
                    }
                ]
            }
        ]
    }

});