/*
 * File: app/view/aboutApp.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pdsencha.view.aboutApp', {
    extend: 'Ext.Panel',
    alias: 'widget.aboutapp',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label'
    ],

    config: {
        padding: '1.2em',
        scrollable: true,
        cls: 'info-panel',
        itemId:'pnl_aboutapp',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.animateActiveItem('mainview', { type: 'slide', direction: 'right' });
                        },
                        docked: 'left',
                        itemId: 'btnback',
                        padding: 5,
                        ui: 'back',
                        text: '返回',
                        style:{
                            'font-size':'1em'
                        }
                    },
                    {
                        xtype: 'spacer',
                        docked: 'right',
                        width: 50
                    },
                    {
                        xtype: 'label',
                        html: '关于APP',
                        style: {
                            color: '#FFF',
                            'font-size': '1em',
                            'text-align': 'center'
                        },
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'label',
                html: '<div style="padding-bottom: 0.5em;text-indent: 1em">本APP是一款产后抑郁症预防和诊断工具。</div>' +
                    '<div style="padding-bottom: 5px;text-indent: 1em">诊断部分采用PHQ-9度量表，其源自于13年5月发布的美国《精神疾病诊断与统计手册》第5版（DSM-5）中关于抑郁症的诊断标准，' +
                    '兼有筛查抑郁症和评估抑郁严重程度的双重作用，具有良好的信度及效度。</div>' +
                    '<div style="padding-bottom: 5px;text-indent: 1em">通过详实的资料和图片，展示产后抑郁症形成的原因以及有效的预防方法，帮助正受产后抑郁困扰的患者逐步摆脱困境。</div>' +
                    '<br>' +
                    '<div style="font-weight: bold;color: orangered">本应用由中华育儿协会赞助，并提供资讯内容支持！</div>' +
                    '<br>' +
                    '<div style="font-weight: bold">鸣谢：</div>' +
                    '<div style="padding-left: 2em">' +
                    '<li>中华育儿协会</li>' +
                    '<li>国际母乳会</li>' +
                    '<li>中华医学会精神病学分会</li>' +
                    '</div>' ,
                itemId: 'lbl_aboutapp'
            }
        ]
    }

});