/*
 * File: app/view/TestResultPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pdsencha.view.HasRecordPanel', {
    extend: 'Ext.Container',
    xtype: 'hasrecordpanel',
    alias: 'widget.hasrecordpanel',

    requires: [
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        testresult: {
            
        },
		defaults:{
			style: {
				'background-color': '#67c52f',
				color: '#FFF'
			}
		},
		height:'100%',
        items: [
            {
                xtype: 'container',
                height: '3em',
                id: 'container',
                items: [
                    {
                        xtype: 'label',
                        centered: true,
                        html: '测试结果',
                        style: {
                            'font-size': '1.5em'
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                height: '2.5em',
                style: {
                    'background-color': '#43b500',
                    color: '#FFF',
                    margin: 'auto'
                },
                items: [
                    {
                        xtype: 'label',
                        docked: 'right',
                        height: '100%',
                        html: '重度抑郁',
                        id: 'resultstr',
                        style: {
                            'text-align': 'center',
                            color: '#d50000',
                            padding: '0.5em'
                        }
                    },
                    {
                        xtype: 'button',
                        docked: 'left',
                        height: '100%',
                        itemId: 'mybutton',
                        style: {
                            'font-size': '0.8em',
                            color: '#FFF',
                            'text-align': 'left',
                            padding: '0.5em'
                        },
                        ui: 'plain',
                        iconCls: 'time',
                        text: ''
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: '100%',
                        html: '2013年12月16日<br>13:01',
                        id: 'createdate',
                        style: {
                            'font-size': '0.8em',
                            padding: '0.2em'
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                height: '4em',
                items: [
                    {
						xtype: 'label',
						html: '18/27',
						id: 'resultscore',
						style: {
							'font-size': '3em',
							'text-align': 'center',
							'line-height': '1.5em'
						}
                    }
                ]
            },
            {
                xtype: 'panel',
                height: '1.5em',
                items: [
                    {
                        xtype: 'panel',
                        centered: false,
                        height: '100%',
                        margin: 'auto',
                        style: {
                            'background-color': '#67cfff'
                        },
                        width: '70%',
                        zIndex: 99,
                        items: [
                            {
                                xtype: 'component',
                                centered: false,
                                height: '100%',
                                id: 'resultscoreline',
                                style: {
                                    'background-color': '#FFF'
                                },
                                width: '30%',
                                zIndex: 100
                            }
                        ]
                    }

                ]
            },
            {
                xtype: 'panel',
                height: '100%',
                scrollable: true,
                items: [
                    {
                        xtype: 'label',
                        centered: false,
                        docked: 'top',
                        html: '分数意味着什么？',
                        style: {
                            'font-size': '1em',
                            'text-align': 'left',
                            'padding-top': '1em',
                            'padding-left': '2em',
                            'padding-right': '2em'
                        }
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        html: '0分代表没有抑郁',
                        id: 'scoredescription',
                        style: {
                            'font-size': '1em',
                            'text-align': 'left',
                            'padding-top': '0.3em',
                            'padding-left': '2em',
                            'padding-right': '2em'
                        }
                    },
                    {
                        xtype: 'label',
                        height: '100%',
                        html: '需要告诉朋友你现在的感受！',
                        id: 'resultdescription',
                        style: {
                            'font-size': '1em',
                            'text-align': 'left',
                            'padding-top': '0.8em',
                            'padding-left': '2em',
                            'padding-right': '2em'
                        }
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonHistoryCommand',
                event: 'HistoryCommand',
                delegate: '#mybutton'
            }
        ]
    },

    onMybuttonHistoryCommand: function(button) {

    },
	getScoreStr: function(score)
	{
		var resultscore = score;
		var resultlist = [
			{minscore: 0,maxscore: 4,level: "没有抑郁", scoreinfo:"0-4分代表您一切正常", description: "继续保持良好的心态，并积极帮助其他抑郁患者！"},
			{minscore: 5,maxscore: 9,level: "轻度抑郁", scoreinfo:"5-9分代表您轻度抑郁", description: "多回忆一下曾经令您快乐的事情，并继续观察：随访时复查PHQ-9！"},
			{minscore: 10,maxscore: 14,level: "中度抑郁", scoreinfo:"10-14分代表您有中度抑郁", description: "多与身边的亲人和朋友联系，并告诉他们您现在的感受；同时制定治疗计划,考虑咨询、家访和药物治疗！"},
			{minscore: 15,maxscore: 19,level: "中重度抑郁", scoreinfo:"15-19分代表您有中重度抑郁", description: "放松心情，认识到抑郁症可以通过调整自己的心态而得到改善；同时积极药物治疗和心理治疗！"},
			{minscore: 20,maxscore: 27,level: "重度抑郁", scoreinfo:"20-27分代表您有重度抑郁", description: "立即治疗，首先选择药物,若严重损伤或对治疗无效,建议转移至精神疾病专家,进行心理治疗和综合治疗！"}
		];
        console.log("getScoreStr:" + resultscore);
		
		//计算测试结果
		var result = undefined;
		Ext.each(resultlist, function(item, index, allItems) {
			if(item.minscore <= resultscore && item.maxscore >= resultscore)
			{
				result = item;
			}
		});
		return result;
	},
	setRecord: function(record)
	{
        //初始化界面
        if(record && record.data)
        {
			this.testresult = record;
            if(record.data.dateCreated)
            {
				var testdate = record.data.dateCreated;
				var datestr = testdate.getFullYear().toString() + '年' 
						+ (testdate.getMonth()+1).toString() + '月' 
						+ testdate.getDate().toString() + '日'
						+ '<br>'
						+ testdate.getHours().toString() + '点'
						+ testdate.getMinutes().toString() + '分'
						+ testdate.getSeconds().toString() + '秒';
                this.down('#createdate').setHtml(datestr);
            }
            if(record.data.score)
            {
                this.down('#resultscore').setHtml(record.data.score.toString() + '/27');
                this.down('#resultscoreline').setWidth((record.data.score/27 * 100).toString() + '%');
				var resultitem = this.getScoreStr(record.data.score);
                this.down('#resultstr').setHtml(resultitem.level);
                this.down('#scoredescription').setHtml(resultitem.scoreinfo);
                this.down('#resultdescription').setHtml(resultitem.description);
            }
        }
	},

    initialize: function() {
        this.callParent();

        //初始化界面
        if(this.testresult)
        {
			setRecord(testresult);
        }
    }

});