/*
 * File: app/view/moreInfo.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pdsencha.view.moreInfo', {
    extend: 'Ext.Container',
    alias: 'widget.moreinfo',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.animateActiveItem('mainview', { type: 'slide', direction: 'right' });
                        },
                        docked: 'left',
                        itemId: 'btnback',
                        padding: 5,
                        ui: 'back',
                        text: '返回'
                    },
                    {
                        xtype: 'spacer',
                        docked: 'right',
                        width: 50
                    },
                    {
                        xtype: 'label',
                        html: '产后抑郁知识',
                        style: {
                            color: '#FFF',
                            'font-size': '1em',
                            'text-align': 'center'
                        },
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'list',
                height: '100%',
                width: '100%',
                itemId: 'links',
                disableSelection: true,
                data: [
                    {
                        name: 'WHO-世界卫生组织(中文)',
                        img: './resources/images/who.jpg',
                        url: 'http://www.who.int/topics/depression/zh/index.html'
                    },
                    {
                        name: 'MHA-美国心理健康中心(english)',
                        img: './resources/images/mha.png',
                        url: 'http://mentalhealthamerica.net/'
                    },
                    {
                        name: 'WebMD-在线健康管理中心(english)',
                        img: './resources/images/webmd.jpg',
                        url: 'http://www.webmd.com/depression/default.htm'
                    },
                    {
                        name: 'NIH-美国国立卫生研究院(english)',
                        img: './resources/images/NIH.png',
                        url: 'http://www.who.int/topics/depression/zh/index.html'
                    },
                    {
                        name: 'DRC-斯坦福大学抑郁症临床研究院(english)',
                        img: './resources/images/DRC.png',
                        url: 'http://drc.stanford.edu/'
                    },
                    {
                        name: '中华育儿协会(中文)',
                        img: './resources/images/yexh.png',
                        url: 'http://yuerxh.org/'
                    }
                ],
                itemTpl: [
                    '<div>',
                    '    <img src="{img]}" style="padding-bottom:0.5em" />',
                    '    <h2>{name}</h2>',
                    '</div>'
                ]
            }
        ],
        listeners: [{
            delegate: "#links",
            event: "itemtap",
            fn: function (item,  index, target, record, e, eOpts) {
                console.log(record.data.url);
                window.open(record.data.url, '_system');
                console.log("moreList itemtap");
                console.log(record);
            }
        }]
    }
});